Cambio el color de algunas letras de informacion para que queden con …
ezequielmonachesi/pokemon pull request #16
Opened 2023-02-21 15:27 UTC by silviojrcc

…el tema oscuro .
Ahora el texto queda legible.

2023-02-21 20:03 UTC, ezequielmonachesi approved these changes
Quedaron bien las letras negras. 👍

2023-02-21 20:55 UTC, NahuFed commented on pages/detallesPokemon.html
> +                    <i class="bi bi-gender-female text-black" text-black></i>
se repite la clase text-black fuera del " ", si bien no causa conflicto no deberia ir

2023-02-21 20:56 UTC, NahuFed requested changes
fijate en la linea 122 te deje un comentario

2023-02-22 20:03 UTC, silviojrcc commented on pages/detallesPokemon.html
> +                    <i class="bi bi-gender-female text-black" text-black></i>
Ahí lo modifiqué

2023-02-22 20:05 UTC, NahuFed approved these changes
🥇

2023-02-22 20:07 UTC, merged